use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMAudioPlayerVCManager_Example' do
  pod 'AHFMAudioPlayerVCManager', :path => '../'

  target 'AHFMAudioPlayerVCManager_Tests' do
    inherit! :search_paths

    
  end
end
